### ISSUE TITLE
Not sure how to fix addOverloadOperators

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#22]
git checkout addOverloadedOperators 
cgemController.py: needs merge
convertRaDecToCgemUnits.py: needs merge
error: you need to resolve your current index first
steele@steele:~/git/steelewool/cgem-controller$ git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by zcsteele** [comment]
I did a rebase to bring some of the commits from master into addOverloadOperators; that sometimes makes the commit history a bit messy. If you haven't made any code changes / commits to that branch, you should be able to update your local repo with `git fetch` and `git reset --hard origin/master` (or origin/addOverloadOperators, depending on which branch you're trying to update).The second command will wipe out any local changes that haven't been committed or stashed, so don't do that if you have changes you want to keep.                                                                                                                                                                                                                 From: steelewoolSent: Saturday, September 22, 2018 9:18 PMTo: steelewool/cgem-controllerReply To: steelewool/cgem-controllerCc: SubscribedSubject: [steelewool/cgem-controller] Not sure how to fix addOverloadOperators (#22)git checkout addOverloadedOperators
cgemController.py: needs merge
convertRaDecToCgemUnits.py: needs merge
error: you need to resolve your current index first
steele@steele:~/git/steelewool/cgem-controller$ git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm '
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/steelewool/cgem-controller","title":"steelewool/cgem-controller","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/steelewool/cgem-controller"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Not sure how to fix addOverloadOperators (#22)"}],"action":{"name":"View Issue","url":"https://github.com/steelewool/cgem-controller/issues/22"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/steelewool/cgem-controller/issues/22",
"url": "https://github.com/steelewool/cgem-controller/issues/22",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Not sure how to fix addOverloadOperators (#22)",
"sections": [
{
"text": "",
"activityTitle": "**steelewool**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@steelewool",
"facts": [
{
"name": "Repository: ",
"value": "steelewool/cgem-controller"
},
{
"name": "Issue #: ",
"value": 22
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"steelewool/cgem-controller\",\n\"issueId\": 22,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"steelewool/cgem-controller\",\n\"issueId\": 22\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/steelewool/cgem-controller/issues/22"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 383137055\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by RobSteele49** [comment]
I'll handle this tomorrow. Thanks for the information.

On September 22, 2018, at 9:37 PM, Zach Steele <notifications@github.com> wrote:

I did a rebase to bring some of the commits from master into addOverloadOperators; that sometimes makes the commit history a bit messy. If you haven't made any code changes / commits to that branch, you should be able to update your local repo with `git fetch` and `git reset --hard origin/master` (or origin/addOverloadOperators, depending on which branch you're trying to update).The second command will wipe out any local changes that haven't been committed or stashed, so don't do that if you have changes you want to keep. From: steelewoolSent: Saturday, September 22, 2018 9:18 PMTo: steelewool/cgem-controllerReply To: steelewool/cgem-controllerCc: SubscribedSubject: [steelewool/cgem-controller] Not sure how to fix addOverloadOperators (#22)git checkout addOverloadedOperators
cgemController.py: needs merge
convertRaDecToCgemUnits.py: needs merge
error: you need to resolve your current index first
steele@steele:~/git/steelewool/cgem-controller$ git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm '
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/steelewool/cgem-controller","title":"steelewool/cgem-controller","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action";:{"name":"Open in GitHub","url":"https://github.com/steelewool/cgem-controller";}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Not sure how to fix addOverloadOperators (#22)"}],"action":{"name":"View Issue","url":"https://github.com/steelewool/cgem-controller/issues/22";}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/steelewool/cgem-controller/issues/22";,
"url": "https://github.com/steelewool/cgem-controller/issues/22";,
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions";,
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Not sure how to fix addOverloadOperators (#22)",
"sections": [
{
"text": "",
"activityTitle": "**steelewool**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png";,
"activitySubtitle": "@steelewool",
"facts": [
{
"name": "Repository: ",
"value": "steelewool/cgem-controller"
},
{
"name": "Issue #: ",
"value": 22
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"steelewool/cgem-controller\",\n\"issueId\": 22,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"steelewool/cgem-controller\",\n\"issueId\": 22\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/steelewool/cgem-controller/issues/22";
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 383137055\n}"
}
],
"themeColor": "26292E"
}
] 

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/steelewool/cgem-controller","title":"steelewool/cgem-controller","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/steelewool/cgem-controller">https://github.com/steelewool/cgem-controller</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zcsteele in #22: I did a rebase to bring some of the commits from master into addOverloadOperators; that sometimes makes the commit history a bit messy. If you haven't made any code changes / commits to that branch, you should be able to update your local repo with `git fetch` and `git reset --hard origin/master` (or origin/addOverloadOperators, depending on which branch you're trying to update).The second command will wipe out any local changes that haven't been committed or stashed, so don't do that if you have changes you want to keep. From: steelewoolSent: Saturday, September 22, 2018 9:18 PMTo: steelewool/cgem-controllerReply To: steelewool/cgem-controllerCc: SubscribedSubject: [steelewool/cgem-controller] Not sure how to fix addOverloadOperators (#22)git checkout addOverloadedOperators\<a href="http://ncgemController.py">ncgemController.py</a>: needs merge\<a href="http://nconvertRaDecToCgemUnits.py">nconvertRaDecToCgemUnits.py</a>: needs merge\nerror: you need to resolve your current index first\nsteele@steele:~/git/steelewool/cgem-controller$ git pull\nerror: Pulling is not possible because you have unmerged files.\nhint: Fix them up in the work tree, and then use 'git add/rm '\nhint: as appropriate to mark resolution and make a commit.\nfatal: Exiting because of an unresolved conflict.\n\n—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.\n{\"api_version\":\"1.0\",\"publisher\":{\"api_key\":\"05dde50f1d1a384dd78767c55493e4bb\",\"name\":\"GitHub\"},\"entity\":{\"external_key\":\"github/steelewool/cgem-controller\",\"title\":\"steelewool/cgem-controller\",\"subtitle\":\"GitHub repository\",\"main_image_url\":\"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>\",\"avatar_image_url\":\"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>\",\"action\":{\"name\":\"Open in GitHub\",\"url\":\"<a href="https://github.com/steelewool/cgem-controller">https://github.com/steelewool/cgem-controller</a>\"}},\"updates\":{\"snippets\":[{\"icon\":\"DESCRIPTION\",\"message\":\"Not sure how to fix addOverloadOperators (#22)\"}],\"action\":{\"name\":\"View Issue\",\"url\":\"<a href="https://github.com/steelewool/cgem-controller/issues/22">https://github.com/steelewool/cgem-controller/issues/22</a>\"}}}\n[\n{\n\"@context\": \"<a href="http://schema.org">http://schema.org</a>\",\n\"@type\": \"EmailMessage\",\n\"potentialAction\": {\n\"@type\": \"ViewAction\",\n\"target\": \"<a href="https://github.com/steelewool/cgem-controller/issues/22">https://github.com/steelewool/cgem-controller/issues/22</a>\",\n\"url\": \"<a href="https://github.com/steelewool/cgem-controller/issues/22">https://github.com/steelewool/cgem-controller/issues/22</a>\",\n\"name\": \"View Issue\"\n},\n\"description\": \"View this Issue on GitHub\",\n\"publisher\": {\n\"@type\": \"Organization\",\n\"name\": \"GitHub\",\n\"url\": \"<a href="https://github.com">https://github.com</a>\"\n}\n},\n{\n\"@type\": \"MessageCard\",\n\"@context\": \"<a href="http://schema.org/extensions">http://schema.org/extensions</a>\",\n\"hideOriginalBody\": \"false\",\n\"originator\": \"AF6C5A86-E920-430C-9C59-A73278B5EFEB\",\n\"title\": \"Not sure how to fix addOverloadOperators (#22)\",\n\"sections\": [\n{\n\"text\": \"\",\n\"activityTitle\": \"**steelewool**\",\n\"activityImage\": \"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>\",\n\"activitySubtitle\": \"@steelewool\",\n\"facts\": [\n{\n\"name\": \"Repository: \",\n\"value\": \"steelewool/cgem-controller\"\n},\n{\n\"name\": \"Issue #: \",\n\"value\": 22\n}\n]\n}\n],\n\"potentialAction\": [\n{\n\"name\": \"Add a comment\",\n\"@type\": \"ActionCard\",\n\"inputs\": [\n{\n\"isMultiLine\": true,\n\"@type\": \"TextInput\",\n\"id\": \"IssueComment\",\n\"isRequired\": false\n}\n],\n\"actions\": [\n{\n\"name\": \"Comment\",\n\"@type\": \"HttpPOST\",\n\"target\": \"<a href="https://api.github.com">https://api.github.com</a>\",\n\"body\": \"{\\n\\\"commandName\\\": \\\"IssueComment\\\",\\n\\\"repositoryFullName\\\": \\\"steelewool/cgem-controller\\\",\\n\\\"issueId\\\": 22,\\n\\\"IssueComment\\\": \\\"{{IssueComment.value}}\\\"\\n}\"\n}\n]\n},\n{\n\"name\": \"Close issue\",\n\"@type\": \"HttpPOST\",\n\"target\": \"<a href="https://api.github.com">https://api.github.com</a>\",\n\"body\": \"{\\n\\\"commandName\\\": \\\"IssueClose\\\",\\n\\\"repositoryFullName\\\": \\\"steelewool/cgem-controller\\\",\\n\\\"issueId\\\": 22\\n}\"\n},\n{\n\"targets\": [\n{\n\"os\": \"default\",\n\"uri\": \"<a href="https://github.com/steelewool/cgem-controller/issues/22">https://github.com/steelewool/cgem-controller/issues/22</a>\"\n}\n],\n\"@type\": \"OpenUri\",\n\"name\": \"View on GitHub\"\n},\n{\n\"name\": \"Unsubscribe\",\n\"@type\": \"HttpPOST\",\n\"target\": \"<a href="https://api.github.com">https://api.github.com</a>\",\n\"body\": \"{\\n\\\"commandName\\\": \\\"MuteNotification\\\",\\n\\\"threadId\\\": 383137055\\n}\"\n}\n],\n\"themeColor\": \"26292E\"\n}\n]"}],"action":{"name":"View Issue","url":"<a href="https://github.com/steelewool/cgem-controller/issues/22#issuecomment-423791383">https://github.com/steelewool/cgem-controller/issues/22#issuecomment-423791383</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/steelewool/cgem-controller/issues/22#issuecomment-423791383">https://github.com/steelewool/cgem-controller/issues/22#issuecomment-423791383</a>", "url": "<a href="https://github.com/steelewool/cgem-controller/issues/22#issuecomment-423791383">https://github.com/steelewool/cgem-controller/issues/22#issuecomment-423791383</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } }, { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [steelewool/cgem-controller] Not sure how to fix addOverloadOperators (#22)", "sections": [ { "text": "", "activityTitle": "**Zach Steele**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@zcsteele", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"steelewool/cgem-controller\",\n\"issueId\": 22,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"steelewool/cgem-controller\",\n\"issueId\": 22\n}" }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/steelewool/cgem-controller/issues/22#issuecomment-423791383">https://github.com/steelewool/cgem-controller/issues/22#issuecomment-423791383</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 383137055\n}" } ], "themeColor": "26292E" } ]

**Comment by steelewool** [comment]
@zcsteele This appears to be resolved - so I'll close this issue for now.
