### ISSUE TITLE
Zach: Confirm merge into master looks OK to you

### ISSUE THREAD

**Issue by steelewool** [steelewool/cgem-controller#27]
I just merged, and resolved conflicts on the cgemController.py program. Can you make sure that I did not break any of you code by doing this master?

**Comment by zcsteele** [comment]
The code to initialized the serial port interface object (`ser`) is still commented out - lines 16-20 in `cgemController.py` https://github.com/steelewool/cgem-controller/blob/master/cgemController.py#L16

It should be fine once those are un-commented.

Also, you can request a review through the GitHub pull request before merging it, rather than generating a separate ticket for the review.

**Comment by RobSteele49** [comment]
I did not know this - but thanks for the info and I'll request reviews
using this mechanism in the future.

**Comment by steelewool** [comment]
Doesn't appear to be an issue any more. Will close for now.
